name: go_server
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.1
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^11.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:

ffigen:
  name: GoServerBind
  description: Bindings to go_server library.
  output: 'lib/core/ffi/goserver_bind.dart'
  headers:
    entry-points:
      - 'src/include/go_server.h'
